server:
  port: 9000

spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    order-service: /gateway/order/**
    product-service: /gateway/product/**
  ignored-patterns: /*-service/**
  sensitive-headers: